baseURL: "https://mafyuh.com/"
title: "Mafyuh's Blog"
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON


params:
  env: production
  title: "Mafyuh's Blog"
  description: "A blog by Mafyuh"
  keywords: ["Blog", "Portfolio", "PaperMod"]
  author: "Matt"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  socialIcons:
    - name: reddit
      url: "https://reddit.com/user/Mafyuh"
    - name: gitea
      url: "https://git.mafyuh.dev"
    - name: github
      url: "https://github.com/Mafyuh"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/mafyuhh"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ["title", "permalink", "summary", "content"]
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/favicon/favicon.ico"
    favicon16x16: "/assets/favicon/favicon-16x16.png"
    favicon32x32: "/assets/favicon/favicon-32x32.png"
    apple_touch_icon: "/assets/favicon/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"
  label:
    text: "Mafyuh's Blog"
    icon: /assets/favicon/favicon.svg
    iconHeight: 35
  profileMode:
    enabled: true # needs to be explicitly set
    title: Mafyuh
    subtitle: "Selfhoster - Jr. DevOps Engineer"
    imageUrl: "/assets/favicon/favicon.svg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Mafyuh Logo
    buttons:
      - name: About
        url: about
      - name: Contact
        url: contact
  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    linkFullImages: true # hide on single page

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

markup:
  highlight:
    noClasses: false

